apply plugin: 'com.android.application'

android {
    namespace 'launcher.minimalist.com'
    compileSdkVersion 36
    defaultConfig {
        applicationId "launcher.simple.com.simplelauncher"
        minSdkVersion 4
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
